// ReSharper disable InconsistentNaming
namespace ScriptPlayer.Shared
{
    public static class AwesomeCharacters
    {
        public const string x500px = "\xf26e"; // 500px
        public const string Accessible_Icon = "\xf368"; // Accessible Icon
        public const string Accusoft = "\xf369"; // Accusoft
        public const string Acquisitions_Incorporated = "\xf6af"; // Acquisitions Incorporated
        public const string Ad = "\xf641"; // Ad
        public const string Address_Book = "\xf2b9"; // Address Book
        public const string Address_Card = "\xf2bb"; // Address Card
        public const string Adjust = "\xf042"; // adjust
        public const string Appnet = "\xf170"; // App.net
        public const string Adobe = "\xf778"; // Adobe
        public const string Adversal = "\xf36a"; // Adversal
        public const string Affiliatetheme = "\xf36b"; // affiliatetheme
        public const string Air_Freshener = "\xf5d0"; // Air Freshener
        public const string Airbnb = "\xf834"; // Airbnb
        public const string Algolia = "\xf36c"; // Algolia
        public const string Aligncenter = "\xf037"; // align-center
        public const string Alignjustify = "\xf039"; // align-justify
        public const string Alignleft = "\xf036"; // align-left
        public const string Alignright = "\xf038"; // align-right
        public const string Alipay = "\xf642"; // Alipay
        public const string Allergies = "\xf461"; // Allergies
        public const string Amazon = "\xf270"; // Amazon
        public const string Amazon_Pay = "\xf42c"; // Amazon Pay
        public const string Ambulance = "\xf0f9"; // ambulance
        public const string American_Sign_Language_Interpreting = "\xf2a3"; // American Sign Language Interpreting
        public const string Amilia = "\xf36d"; // Amilia
        public const string Anchor = "\xf13d"; // Anchor
        public const string Android = "\xf17b"; // Android
        public const string Angellist = "\xf209"; // AngelList
        public const string Angle_Double_Down = "\xf103"; // Angle Double Down
        public const string Angle_Double_Left = "\xf100"; // Angle Double Left
        public const string Angle_Double_Right = "\xf101"; // Angle Double Right
        public const string Angle_Double_Up = "\xf102"; // Angle Double Up
        public const string Angledown = "\xf107"; // angle-down
        public const string Angleleft = "\xf104"; // angle-left
        public const string Angleright = "\xf105"; // angle-right
        public const string Angleup = "\xf106"; // angle-up
        public const string Angry_Face = "\xf556"; // Angry Face
        public const string Angry_Creative = "\xf36e"; // Angry Creative
        public const string Angular = "\xf420"; // Angular
        public const string Ankh = "\xf644"; // Ankh
        public const string App_Store = "\xf36f"; // App Store
        public const string Ios_App_Store = "\xf370"; // iOS App Store
        public const string Apper_Systems_Ab = "\xf371"; // Apper Systems AB
        public const string Apple = "\xf179"; // Apple
        public const string Fruit_Apple = "\xf5d1"; // Fruit Apple
        public const string Apple_Pay = "\xf415"; // Apple Pay
        public const string Archive = "\xf187"; // Archive
        public const string Archway = "\xf557"; // Archway
        public const string Alternate_Arrow_Circle_Down = "\xf358"; // Alternate Arrow Circle Down
        public const string Alternate_Arrow_Circle_Left = "\xf359"; // Alternate Arrow Circle Left
        public const string Alternate_Arrow_Circle_Right = "\xf35a"; // Alternate Arrow Circle Right
        public const string Alternate_Arrow_Circle_Up = "\xf35b"; // Alternate Arrow Circle Up
        public const string Arrow_Circle_Down = "\xf0ab"; // Arrow Circle Down
        public const string Arrow_Circle_Left = "\xf0a8"; // Arrow Circle Left
        public const string Arrow_Circle_Right = "\xf0a9"; // Arrow Circle Right
        public const string Arrow_Circle_Up = "\xf0aa"; // Arrow Circle Up
        public const string Arrowdown = "\xf063"; // arrow-down
        public const string Arrowleft = "\xf060"; // arrow-left
        public const string Arrowright = "\xf061"; // arrow-right
        public const string Arrowup = "\xf062"; // arrow-up
        public const string Alternate_Arrows = "\xf0b2"; // Alternate Arrows
        public const string Alternate_Arrows_Horizontal = "\xf337"; // Alternate Arrows Horizontal
        public const string Alternate_Arrows_Vertical = "\xf338"; // Alternate Arrows Vertical
        public const string Artstation = "\xf77a"; // Artstation
        public const string Assistive_Listening_Systems = "\xf2a2"; // Assistive Listening Systems
        public const string Asterisk = "\xf069"; // asterisk
        public const string Asymmetrik_Ltd = "\xf372"; // Asymmetrik, Ltd.
        public const string At = "\xf1fa"; // At
        public const string Atlas = "\xf558"; // Atlas
        public const string Atlassian = "\xf77b"; // Atlassian
        public const string Atom = "\xf5d2"; // Atom
        public const string Audible = "\xf373"; // Audible
        public const string Audio_Description = "\xf29e"; // Audio Description
        public const string Autoprefixer = "\xf41c"; // Autoprefixer
        public const string Avianex = "\xf374"; // avianex
        public const string Aviato = "\xf421"; // Aviato
        public const string Award = "\xf559"; // Award
        public const string Amazon_Web_Services_Aws = "\xf375"; // Amazon Web Services (AWS)
        public const string Baby = "\xf77c"; // Baby
        public const string Baby_Carriage = "\xf77d"; // Baby Carriage
        public const string Backspace = "\xf55a"; // Backspace
        public const string Backward = "\xf04a"; // backward
        public const string Bacon = "\xf7e5"; // Bacon
        public const string Baháí = "\xf666"; // Bahá'í
        public const string Balance_Scale = "\xf24e"; // Balance Scale
        public const string Balance_Scale_Leftweighted = "\xf515"; // Balance Scale (Left-Weighted)
        public const string Balance_Scale_Rightweighted = "\xf516"; // Balance Scale (Right-Weighted)
        public const string Ban = "\xf05e"; // ban
        public const string Bandaid = "\xf462"; // Band-Aid
        public const string Bandcamp = "\xf2d5"; // Bandcamp
        public const string Barcode = "\xf02a"; // barcode
        public const string Bars = "\xf0c9"; // Bars
        public const string Baseball_Ball = "\xf433"; // Baseball Ball
        public const string Basketball_Ball = "\xf434"; // Basketball Ball
        public const string Bath = "\xf2cd"; // Bath
        public const string Battery_Empty = "\xf244"; // Battery Empty
        public const string Battery_Full = "\xf240"; // Battery Full
        public const string Battery_12_Full = "\xf242"; // Battery 1/2 Full
        public const string Battery_14_Full = "\xf243"; // Battery 1/4 Full
        public const string Battery_34_Full = "\xf241"; // Battery 3/4 Full
        public const string Battlenet = "\xf835"; // Battle.net
        public const string Bed = "\xf236"; // Bed
        public const string Beer = "\xf0fc"; // beer
        public const string Behance = "\xf1b4"; // Behance
        public const string Behance_Square = "\xf1b5"; // Behance Square
        public const string Bell = "\xf0f3"; // bell
        public const string Bell_Slash = "\xf1f6"; // Bell Slash
        public const string Bezier_Curve = "\xf55b"; // Bezier Curve
        public const string Bible = "\xf647"; // Bible
        public const string Bicycle = "\xf206"; // Bicycle
        public const string Biking = "\xf84a"; // Biking
        public const string Bimobject = "\xf378"; // BIMobject
        public const string Binoculars = "\xf1e5"; // Binoculars
        public const string Biohazard = "\xf780"; // Biohazard
        public const string Birthday_Cake = "\xf1fd"; // Birthday Cake
        public const string Bitbucket = "\xf171"; // Bitbucket
        public const string Bitcoin = "\xf379"; // Bitcoin
        public const string Bity = "\xf37a"; // Bity
        public const string Font_Awesome_Black_Tie = "\xf27e"; // Font Awesome Black Tie
        public const string Blackberry = "\xf37b"; // BlackBerry
        public const string Blender = "\xf517"; // Blender
        public const string Blender_Phone = "\xf6b6"; // Blender Phone
        public const string Blind = "\xf29d"; // Blind
        public const string Blog = "\xf781"; // Blog
        public const string Blogger = "\xf37c"; // Blogger
        public const string Blogger_B = "\xf37d"; // Blogger B
        public const string Bluetooth = "\xf293"; // Bluetooth
        public const string Bluetooth_2 = "\xf294"; // Bluetooth
        public const string Bold = "\xf032"; // bold
        public const string Lightning_Bolt = "\xf0e7"; // Lightning Bolt
        public const string Bomb = "\xf1e2"; // Bomb
        public const string Bone = "\xf5d7"; // Bone
        public const string Bong = "\xf55c"; // Bong
        public const string Book = "\xf02d"; // book
        public const string Book_Of_The_Dead = "\xf6b7"; // Book of the Dead
        public const string Medical_Book = "\xf7e6"; // Medical Book
        public const string Book_Open = "\xf518"; // Book Open
        public const string Book_Reader = "\xf5da"; // Book Reader
        public const string Bookmark = "\xf02e"; // bookmark
        public const string Bootstrap = "\xf836"; // Bootstrap
        public const string Border_All = "\xf84c"; // Border All
        public const string Border_None = "\xf850"; // Border None
        public const string Border_Style = "\xf853"; // Border Style
        public const string Bowling_Ball = "\xf436"; // Bowling Ball
        public const string Box = "\xf466"; // Box
        public const string Box_Open = "\xf49e"; // Box Open
        public const string Boxes = "\xf468"; // Boxes
        public const string Braille = "\xf2a1"; // Braille
        public const string Brain = "\xf5dc"; // Brain
        public const string Bread_Slice = "\xf7ec"; // Bread Slice
        public const string Briefcase = "\xf0b1"; // Briefcase
        public const string Medical_Briefcase = "\xf469"; // Medical Briefcase
        public const string Broadcast_Tower = "\xf519"; // Broadcast Tower
        public const string Broom = "\xf51a"; // Broom
        public const string Brush = "\xf55d"; // Brush
        public const string Btc = "\xf15a"; // BTC
        public const string Buffer = "\xf837"; // Buffer
        public const string Bug = "\xf188"; // 
        public const string Building = "\xf1ad"; // Building
        public const string Bullhorn = "\xf0a1"; // bullhorn
        public const string Bullseye = "\xf140"; // Bullseye
        public const string Burn = "\xf46a"; // Burn
        public const string Büromöbelexperte_Gmbh_Co_Kg = "\xf37f"; // Büromöbel-Experte GmbH & Co. KG.
        public const string Bus = "\xf207"; // Bus
        public const string Bus_Alt = "\xf55e"; // Bus Alt
        public const string Business_Time = "\xf64a"; // Business Time
        public const string Buy_N_Large = "\xf8a6"; // Buy n Large
        public const string Buysellads = "\xf20d"; // BuySellAds
        public const string Calculator = "\xf1ec"; // Calculator
        public const string Calendar = "\xf133"; // Calendar
        public const string Alternate_Calendar = "\xf073"; // Alternate Calendar
        public const string Calendar_Check = "\xf274"; // Calendar Check
        public const string Calendar_With_Day_Focus = "\xf783"; // Calendar with Day Focus
        public const string Calendar_Minus = "\xf272"; // Calendar Minus
        public const string Calendar_Plus = "\xf271"; // Calendar Plus
        public const string Calendar_Times = "\xf273"; // Calendar Times
        public const string Calendar_With_Week_Focus = "\xf784"; // Calendar with Week Focus
        public const string Camera = "\xf030"; // camera
        public const string Retro_Camera = "\xf083"; // Retro Camera
        public const string Campground = "\xf6bb"; // Campground
        public const string Canadian_Maple_Leaf = "\xf785"; // Canadian Maple Leaf
        public const string Candy_Cane = "\xf786"; // Candy Cane
        public const string Cannabis = "\xf55f"; // Cannabis
        public const string Capsules = "\xf46b"; // Capsules
        public const string Car = "\xf1b9"; // Car
        public const string Alternate_Car = "\xf5de"; // Alternate Car
        public const string Car_Battery = "\xf5df"; // Car Battery
        public const string Car_Crash = "\xf5e1"; // Car Crash
        public const string Car_Side = "\xf5e4"; // Car Side
        public const string Caravan = "\xf8ff"; // Caravan
        public const string Caret_Down = "\xf0d7"; // Caret Down
        public const string Caret_Left = "\xf0d9"; // Caret Left
        public const string Caret_Right = "\xf0da"; // Caret Right
        public const string Caret_Square_Down = "\xf150"; // Caret Square Down
        public const string Caret_Square_Left = "\xf191"; // Caret Square Left
        public const string Caret_Square_Right = "\xf152"; // Caret Square Right
        public const string Caret_Square_Up = "\xf151"; // Caret Square Up
        public const string Caret_Up = "\xf0d8"; // Caret Up
        public const string Carrot = "\xf787"; // Carrot
        public const string Shopping_Cart_Arrow_Down = "\xf218"; // Shopping Cart Arrow Down
        public const string Add_To_Shopping_Cart = "\xf217"; // Add to Shopping Cart
        public const string Cash_Register = "\xf788"; // Cash Register
        public const string Cat = "\xf6be"; // Cat
        public const string Amazon_Pay_Credit_Card = "\xf42d"; // Amazon Pay Credit Card
        public const string American_Express_Credit_Card = "\xf1f3"; // American Express Credit Card
        public const string Apple_Pay_Credit_Card = "\xf416"; // Apple Pay Credit Card
        public const string Diners_Club_Credit_Card = "\xf24c"; // Diner's Club Credit Card
        public const string Discover_Credit_Card = "\xf1f2"; // Discover Credit Card
        public const string Jcb_Credit_Card = "\xf24b"; // JCB Credit Card
        public const string Mastercard_Credit_Card = "\xf1f1"; // MasterCard Credit Card
        public const string Paypal_Credit_Card = "\xf1f4"; // Paypal Credit Card
        public const string Stripe_Credit_Card = "\xf1f5"; // Stripe Credit Card
        public const string Visa_Credit_Card = "\xf1f0"; // Visa Credit Card
        public const string Centercode = "\xf380"; // Centercode
        public const string Centos = "\xf789"; // Centos
        public const string Certificate = "\xf0a3"; // certificate
        public const string Chair = "\xf6c0"; // Chair
        public const string Chalkboard = "\xf51b"; // Chalkboard
        public const string Chalkboard_Teacher = "\xf51c"; // Chalkboard Teacher
        public const string Charging_Station = "\xf5e7"; // Charging Station
        public const string Area_Chart = "\xf1fe"; // Area Chart
        public const string Bar_Chart = "\xf080"; // Bar Chart
        public const string Line_Chart = "\xf201"; // Line Chart
        public const string Pie_Chart = "\xf200"; // Pie Chart
        public const string Check = "\xf00c"; // Check
        public const string Check_Circle = "\xf058"; // Check Circle
        public const string Double_Check = "\xf560"; // Double Check
        public const string Check_Square = "\xf14a"; // Check Square
        public const string Cheese = "\xf7ef"; // Cheese
        public const string Chess = "\xf439"; // Chess
        public const string Chess_Bishop = "\xf43a"; // Chess Bishop
        public const string Chess_Board = "\xf43c"; // Chess Board
        public const string Chess_King = "\xf43f"; // Chess King
        public const string Chess_Knight = "\xf441"; // Chess Knight
        public const string Chess_Pawn = "\xf443"; // Chess Pawn
        public const string Chess_Queen = "\xf445"; // Chess Queen
        public const string Chess_Rook = "\xf447"; // Chess Rook
        public const string Chevron_Circle_Down = "\xf13a"; // Chevron Circle Down
        public const string Chevron_Circle_Left = "\xf137"; // Chevron Circle Left
        public const string Chevron_Circle_Right = "\xf138"; // Chevron Circle Right
        public const string Chevron_Circle_Up = "\xf139"; // Chevron Circle Up
        public const string Chevrondown = "\xf078"; // chevron-down
        public const string Chevronleft = "\xf053"; // chevron-left
        public const string Chevronright = "\xf054"; // chevron-right
        public const string Chevronup = "\xf077"; // chevron-up
        public const string Child = "\xf1ae"; // Child
        public const string Chrome = "\xf268"; // Chrome
        public const string Chromecast = "\xf838"; // Chromecast
        public const string Church = "\xf51d"; // Church
        public const string Circle = "\xf111"; // Circle
        public const string Circle_Notched = "\xf1ce"; // Circle Notched
        public const string City = "\xf64f"; // City
        public const string Medical_Clinic = "\xf7f2"; // Medical Clinic
        public const string Clipboard = "\xf328"; // Clipboard
        public const string Clipboard_With_Check = "\xf46c"; // Clipboard with Check
        public const string Clipboard_List = "\xf46d"; // Clipboard List
        public const string Clock = "\xf017"; // Clock
        public const string Clone = "\xf24d"; // Clone
        public const string Closed_Captioning = "\xf20a"; // Closed Captioning
        public const string Cloud = "\xf0c2"; // Cloud
        public const string Alternate_Cloud_Download = "\xf381"; // Alternate Cloud Download
        public const string Cloud_With_A_Chance_Of_Meatball = "\xf73b"; // Cloud with (a chance of) Meatball
        public const string Cloud_With_Moon = "\xf6c3"; // Cloud with Moon
        public const string Cloud_With_Moon_And_Rain = "\xf73c"; // Cloud with Moon and Rain
        public const string Cloud_With_Rain = "\xf73d"; // Cloud with Rain
        public const string Cloud_With_Heavy_Showers = "\xf740"; // Cloud with Heavy Showers
        public const string Cloud_With_Sun = "\xf6c4"; // Cloud with Sun
        public const string Cloud_With_Sun_And_Rain = "\xf743"; // Cloud with Sun and Rain
        public const string Alternate_Cloud_Upload = "\xf382"; // Alternate Cloud Upload
        public const string Cloudscalech = "\xf383"; // cloudscale.ch
        public const string Cloudsmith = "\xf384"; // Cloudsmith
        public const string Cloudversify = "\xf385"; // cloudversify
        public const string Cocktail = "\xf561"; // Cocktail
        public const string Code = "\xf121"; // Code
        public const string Code_Branch = "\xf126"; // Code Branch
        public const string Codepen = "\xf1cb"; // Codepen
        public const string Codie_Pie = "\xf284"; // Codie Pie
        public const string Coffee = "\xf0f4"; // Coffee
        public const string Cog = "\xf013"; // cog
        public const string Cogs = "\xf085"; // cogs
        public const string Coins = "\xf51e"; // Coins
        public const string Columns = "\xf0db"; // Columns
        public const string Comment = "\xf075"; // comment
        public const string Alternate_Comment = "\xf27a"; // Alternate Comment
        public const string Comment_Dollar = "\xf651"; // Comment Dollar
        public const string Comment_Dots = "\xf4ad"; // Comment Dots
        public const string Alternate_Medical_Chat = "\xf7f5"; // Alternate Medical Chat
        public const string Comment_Slash = "\xf4b3"; // Comment Slash
        public const string Comments = "\xf086"; // comments
        public const string Comments_Dollar = "\xf653"; // Comments Dollar
        public const string Compact_Disc = "\xf51f"; // Compact Disc
        public const string Compass = "\xf14e"; // Compass
        public const string Compress = "\xf066"; // Compress
        public const string Alternate_Compress = "\xf422"; // Alternate Compress
        public const string Alternate_Compress_Arrows = "\xf78c"; // Alternate Compress Arrows
        public const string Concierge_Bell = "\xf562"; // Concierge Bell
        public const string Confluence = "\xf78d"; // Confluence
        public const string Connect_Develop = "\xf20e"; // Connect Develop
        public const string Contao = "\xf26d"; // Contao
        public const string Cookie = "\xf563"; // Cookie
        public const string Cookie_Bite = "\xf564"; // Cookie Bite
        public const string Copy = "\xf0c5"; // Copy
        public const string Copyright = "\xf1f9"; // Copyright
        public const string Cotton_Bureau = "\xf89e"; // Cotton Bureau
        public const string Couch = "\xf4b8"; // Couch
        public const string Cpanel = "\xf388"; // cPanel
        public const string Creative_Commons = "\xf25e"; // Creative Commons
        public const string Creative_Commons_Attribution = "\xf4e7"; // Creative Commons Attribution
        public const string Creative_Commons_Noncommercial = "\xf4e8"; // Creative Commons Noncommercial
        public const string Creative_Commons_Noncommercial_Euro_Sign = "\xf4e9"; // Creative Commons Noncommercial (Euro Sign)
        public const string Creative_Commons_Noncommercial_Yen_Sign = "\xf4ea"; // Creative Commons Noncommercial (Yen Sign)
        public const string Creative_Commons_No_Derivative_Works = "\xf4eb"; // Creative Commons No Derivative Works
        public const string Creative_Commons_Public_Domain = "\xf4ec"; // Creative Commons Public Domain
        public const string Alternate_Creative_Commons_Public_Domain = "\xf4ed"; // Alternate Creative Commons Public Domain
        public const string Creative_Commons_Remix = "\xf4ee"; // Creative Commons Remix
        public const string Creative_Commons_Share_Alike = "\xf4ef"; // Creative Commons Share Alike
        public const string Creative_Commons_Sampling = "\xf4f0"; // Creative Commons Sampling
        public const string Creative_Commons_Sampling_2 = "\xf4f1"; // Creative Commons Sampling +
        public const string Creative_Commons_Share = "\xf4f2"; // Creative Commons Share
        public const string Creative_Commons_Cc0 = "\xf4f3"; // Creative Commons CC0
        public const string Credit_Card = "\xf09d"; // Credit Card
        public const string Critical_Role = "\xf6c9"; // Critical Role
        public const string Crop = "\xf125"; // crop
        public const string Alternate_Crop = "\xf565"; // Alternate Crop
        public const string Cross = "\xf654"; // Cross
        public const string Crosshairs = "\xf05b"; // Crosshairs
        public const string Crow = "\xf520"; // Crow
        public const string Crown = "\xf521"; // Crown
        public const string Crutch = "\xf7f7"; // Crutch
        public const string Css_3_Logo = "\xf13c"; // CSS 3 Logo
        public const string Alternate_Css3_Logo = "\xf38b"; // Alternate CSS3 Logo
        public const string Cube = "\xf1b2"; // Cube
        public const string Cubes = "\xf1b3"; // Cubes
        public const string Cut = "\xf0c4"; // Cut
        public const string Cuttlefish = "\xf38c"; // Cuttlefish
        public const string Dungeons_Dragons = "\xf38d"; // Dungeons & Dragons
        public const string Dd_Beyond = "\xf6ca"; // D&D Beyond
        public const string Dashcube = "\xf210"; // DashCube
        public const string Database = "\xf1c0"; // Database
        public const string Deaf = "\xf2a4"; // Deaf
        public const string Delicious = "\xf1a5"; // Delicious
        public const string Democrat = "\xf747"; // Democrat
        public const string Deploydog = "\xf38e"; // deploy.dog
        public const string Deskpro = "\xf38f"; // Deskpro
        public const string Desktop = "\xf108"; // Desktop
        public const string Dev = "\xf6cc"; // DEV
        public const string Deviantart = "\xf1bd"; // deviantART
        public const string Dharmachakra = "\xf655"; // Dharmachakra
        public const string Dhl = "\xf790"; // DHL
        public const string Diagnoses = "\xf470"; // Diagnoses
        public const string Diaspora = "\xf791"; // Diaspora
        public const string Dice = "\xf522"; // Dice
        public const string Dice_D20 = "\xf6cf"; // Dice D20
        public const string Dice_D6 = "\xf6d1"; // Dice D6
        public const string Dice_Five = "\xf523"; // Dice Five
        public const string Dice_Four = "\xf524"; // Dice Four
        public const string Dice_One = "\xf525"; // Dice One
        public const string Dice_Six = "\xf526"; // Dice Six
        public const string Dice_Three = "\xf527"; // Dice Three
        public const string Dice_Two = "\xf528"; // Dice Two
        public const string Digg_Logo = "\xf1a6"; // Digg Logo
        public const string Digital_Ocean = "\xf391"; // Digital Ocean
        public const string Digital_Tachograph = "\xf566"; // Digital Tachograph
        public const string Directions = "\xf5eb"; // Directions
        public const string Discord = "\xf392"; // Discord
        public const string Discourse = "\xf393"; // Discourse
        public const string Divide = "\xf529"; // Divide
        public const string Dizzy_Face = "\xf567"; // Dizzy Face
        public const string Dna = "\xf471"; // DNA
        public const string Dochub = "\xf394"; // DocHub
        public const string Docker = "\xf395"; // Docker
        public const string Dog = "\xf6d3"; // Dog
        public const string Dollar_Sign = "\xf155"; // Dollar Sign
        public const string Dolly = "\xf472"; // Dolly
        public const string Dolly_Flatbed = "\xf474"; // Dolly Flatbed
        public const string Donate = "\xf4b9"; // Donate
        public const string Door_Closed = "\xf52a"; // Door Closed
        public const string Door_Open = "\xf52b"; // Door Open
        public const string Dot_Circle = "\xf192"; // Dot Circle
        public const string Dove = "\xf4ba"; // Dove
        public const string Download = "\xf019"; // Download
        public const string Draft2digital = "\xf396"; // Draft2digital
        public const string Drafting_Compass = "\xf568"; // Drafting Compass
        public const string Dragon = "\xf6d5"; // Dragon
        public const string Draw_Polygon = "\xf5ee"; // Draw Polygon
        public const string Dribbble = "\xf17d"; // Dribbble
        public const string Dribbble_Square = "\xf397"; // Dribbble Square
        public const string Dropbox = "\xf16b"; // Dropbox
        public const string Drum = "\xf569"; // Drum
        public const string Drum_Steelpan = "\xf56a"; // Drum Steelpan
        public const string Drumstick_With_Bite_Taken_Out = "\xf6d7"; // Drumstick with Bite Taken Out
        public const string Drupal_Logo = "\xf1a9"; // Drupal Logo
        public const string Dumbbell = "\xf44b"; // Dumbbell
        public const string Dumpster = "\xf793"; // Dumpster
        public const string Dumpster_Fire = "\xf794"; // Dumpster Fire
        public const string Dungeon = "\xf6d9"; // Dungeon
        public const string Dyalog = "\xf399"; // Dyalog
        public const string Earlybirds = "\xf39a"; // Earlybirds
        public const string Ebay = "\xf4f4"; // eBay
        public const string Edge_Browser = "\xf282"; // Edge Browser
        public const string Edit = "\xf044"; // Edit
        public const string Egg = "\xf7fb"; // Egg
        public const string Eject = "\xf052"; // eject
        public const string Elementor = "\xf430"; // Elementor
        public const string Horizontal_Ellipsis = "\xf141"; // Horizontal Ellipsis
        public const string Vertical_Ellipsis = "\xf142"; // Vertical Ellipsis
        public const string Ello = "\xf5f1"; // Ello
        public const string Ember = "\xf423"; // Ember
        public const string Galactic_Empire = "\xf1d1"; // Galactic Empire
        public const string Envelope = "\xf0e0"; // Envelope
        public const string Envelope_Open = "\xf2b6"; // Envelope Open
        public const string Envelope_Opentext = "\xf658"; // Envelope Open-text
        public const string Envelope_Square = "\xf199"; // Envelope Square
        public const string Envira_Gallery = "\xf299"; // Envira Gallery
        public const string EqualsSign = "\xf52c"; // Equals
        public const string Eraser = "\xf12d"; // eraser
        public const string Erlang = "\xf39d"; // Erlang
        public const string Ethereum = "\xf42e"; // Ethereum
        public const string Ethernet = "\xf796"; // Ethernet
        public const string Etsy = "\xf2d7"; // Etsy
        public const string Euro_Sign = "\xf153"; // Euro Sign
        public const string Evernote = "\xf839"; // Evernote
        public const string Alternate_Exchange = "\xf362"; // Alternate Exchange
        public const string Exclamation = "\xf12a"; // exclamation
        public const string Exclamation_Circle = "\xf06a"; // Exclamation Circle
        public const string Exclamation_Triangle = "\xf071"; // Exclamation Triangle
        public const string Expand = "\xf065"; // Expand
        public const string Alternate_Expand = "\xf424"; // Alternate Expand
        public const string Alternate_Expand_Arrows = "\xf31e"; // Alternate Expand Arrows
        public const string Expeditedssl = "\xf23e"; // ExpeditedSSL
        public const string Alternate_External_Link = "\xf35d"; // Alternate External Link
        public const string Alternate_External_Link_Square = "\xf360"; // Alternate External Link Square
        public const string Eye = "\xf06e"; // Eye
        public const string Eye_Dropper = "\xf1fb"; // Eye Dropper
        public const string Eye_Slash = "\xf070"; // Eye Slash
        public const string Facebook = "\xf09a"; // Facebook
        public const string Facebook_F = "\xf39e"; // Facebook F
        public const string Facebook_Messenger = "\xf39f"; // Facebook Messenger
        public const string Facebook_Square = "\xf082"; // Facebook Square
        public const string Fan = "\xf863"; // Fan
        public const string Fantasy_Flightgames = "\xf6dc"; // Fantasy Flight-games
        public const string Fastbackward = "\xf049"; // fast-backward
        public const string Fastforward = "\xf050"; // fast-forward
        public const string Fax = "\xf1ac"; // Fax
        public const string Feather = "\xf52d"; // Feather
        public const string Alternate_Feather = "\xf56b"; // Alternate Feather
        public const string Fedex = "\xf797"; // FedEx
        public const string Fedora = "\xf798"; // Fedora
        public const string Female = "\xf182"; // Female
        public const string Fighterjet = "\xf0fb"; // fighter-jet
        public const string Figma = "\xf799"; // Figma
        public const string File = "\xf15b"; // File
        public const string Alternate_File = "\xf15c"; // Alternate File
        public const string Archive_File = "\xf1c6"; // Archive File
        public const string Audio_File = "\xf1c7"; // Audio File
        public const string Code_File = "\xf1c9"; // Code File
        public const string File_Contract = "\xf56c"; // File Contract
        public const string File_Csv = "\xf6dd"; // File CSV
        public const string File_Download = "\xf56d"; // File Download
        public const string Excel_File = "\xf1c3"; // Excel File
        public const string File_Export = "\xf56e"; // File Export
        public const string Image_File = "\xf1c5"; // Image File
        public const string File_Import = "\xf56f"; // File Import
        public const string File_Invoice = "\xf570"; // File Invoice
        public const string File_Invoice_With_Us_Dollar = "\xf571"; // File Invoice with US Dollar
        public const string Medical_File = "\xf477"; // Medical File
        public const string Alternate_Medical_File = "\xf478"; // Alternate Medical File
        public const string Pdf_File = "\xf1c1"; // PDF File
        public const string Powerpoint_File = "\xf1c4"; // Powerpoint File
        public const string File_Prescription = "\xf572"; // File Prescription
        public const string File_Signature = "\xf573"; // File Signature
        public const string File_Upload = "\xf574"; // File Upload
        public const string Video_File = "\xf1c8"; // Video File
        public const string Word_File = "\xf1c2"; // Word File
        public const string Fill = "\xf575"; // Fill
        public const string Fill_Drip = "\xf576"; // Fill Drip
        public const string Film = "\xf008"; // Film
        public const string Filter = "\xf0b0"; // Filter
        public const string Fingerprint = "\xf577"; // Fingerprint
        public const string Fire = "\xf06d"; // fire
        public const string Alternate_Fire = "\xf7e4"; // Alternate Fire
        public const string Fireextinguisher = "\xf134"; // fire-extinguisher
        public const string Firefox = "\xf269"; // Firefox
        public const string Firefox_Browser = "\xf907"; // Firefox Browser
        public const string First_Aid = "\xf479"; // First Aid
        public const string First_Order = "\xf2b0"; // First Order
        public const string Alternate_First_Order = "\xf50a"; // Alternate First Order
        public const string Firstdraft = "\xf3a1"; // firstdraft
        public const string Fish = "\xf578"; // Fish
        public const string Raised_Fist = "\xf6de"; // Raised Fist
        public const string Flag = "\xf024"; // flag
        public const string Flagcheckered = "\xf11e"; // flag-checkered
        public const string United_States_Of_America_Flag = "\xf74d"; // United States of America Flag
        public const string Flask = "\xf0c3"; // Flask
        public const string Flickr = "\xf16e"; // Flickr
        public const string Flipboard = "\xf44d"; // Flipboard
        public const string Flushed_Face = "\xf579"; // Flushed Face
        public const string Fly = "\xf417"; // Fly
        public const string Folder = "\xf07b"; // Folder
        public const string Folder_Minus = "\xf65d"; // Folder Minus
        public const string Folder_Open = "\xf07c"; // Folder Open
        public const string Folder_Plus = "\xf65e"; // Folder Plus
        public const string Font = "\xf031"; // font
        public const string Font_Awesome = "\xf2b4"; // Font Awesome
        public const string Alternate_Font_Awesome = "\xf35c"; // Alternate Font Awesome
        public const string Font_Awesome_Flag = "\xf425"; // Font Awesome Flag
        public const string Font_Awesome_Full_Logo = "\xf4e6"; // Font Awesome Full Logo
        public const string Fonticons = "\xf280"; // Fonticons
        public const string Fonticons_Fi = "\xf3a2"; // Fonticons Fi
        public const string Football_Ball = "\xf44e"; // Football Ball
        public const string Fort_Awesome = "\xf286"; // Fort Awesome
        public const string Alternate_Fort_Awesome = "\xf3a3"; // Alternate Fort Awesome
        public const string Forumbee = "\xf211"; // Forumbee
        public const string Forward = "\xf04e"; // forward
        public const string Foursquare = "\xf180"; // Foursquare
        public const string Freecodecamp = "\xf2c5"; // freeCodeCamp
        public const string Freebsd = "\xf3a4"; // FreeBSD
        public const string Frog = "\xf52e"; // Frog
        public const string Frowning_Face = "\xf119"; // Frowning Face
        public const string Frowning_Face_With_Open_Mouth = "\xf57a"; // Frowning Face With Open Mouth
        public const string Fulcrum = "\xf50b"; // Fulcrum
        public const string Funnel_Dollar = "\xf662"; // Funnel Dollar
        public const string Futbol = "\xf1e3"; // Futbol
        public const string Galactic_Republic = "\xf50c"; // Galactic Republic
        public const string Galactic_Senate = "\xf50d"; // Galactic Senate
        public const string Gamepad = "\xf11b"; // Gamepad
        public const string Gas_Pump = "\xf52f"; // Gas Pump
        public const string Gavel = "\xf0e3"; // Gavel
        public const string Gem = "\xf3a5"; // Gem
        public const string Genderless = "\xf22d"; // Genderless
        public const string Get_Pocket = "\xf265"; // Get Pocket
        public const string Gg_Currency = "\xf260"; // GG Currency
        public const string Gg_Currency_Circle = "\xf261"; // GG Currency Circle
        public const string Ghost = "\xf6e2"; // Ghost
        public const string Gift = "\xf06b"; // gift
        public const string Gifts = "\xf79c"; // Gifts
        public const string Git = "\xf1d3"; // Git
        public const string Git_Alt = "\xf841"; // Git Alt
        public const string Git_Square = "\xf1d2"; // Git Square
        public const string Github = "\xf09b"; // GitHub
        public const string Alternate_Github = "\xf113"; // Alternate GitHub
        public const string Github_Square = "\xf092"; // GitHub Square
        public const string Gitkraken = "\xf3a6"; // GitKraken
        public const string Gitlab = "\xf296"; // GitLab
        public const string Gitter = "\xf426"; // Gitter
        public const string Glass_Cheers = "\xf79f"; // Glass Cheers
        public const string Martini_Glass = "\xf000"; // Martini Glass
        public const string Alternate_Glass_Martini = "\xf57b"; // Alternate Glass Martini
        public const string Glass_Whiskey = "\xf7a0"; // Glass Whiskey
        public const string Glasses = "\xf530"; // Glasses
        public const string Glide = "\xf2a5"; // Glide
        public const string Glide_G = "\xf2a6"; // Glide G
        public const string Globe = "\xf0ac"; // Globe
        public const string Globe_With_Africa_Shown = "\xf57c"; // Globe with Africa shown
        public const string Globe_With_Americas_Shown = "\xf57d"; // Globe with Americas shown
        public const string Globe_With_Asia_Shown = "\xf57e"; // Globe with Asia shown
        public const string Globe_With_Europe_Shown = "\xf7a2"; // Globe with Europe shown
        public const string Gofore = "\xf3a7"; // Gofore
        public const string Golf_Ball = "\xf450"; // Golf Ball
        public const string Goodreads = "\xf3a8"; // Goodreads
        public const string Goodreads_G = "\xf3a9"; // Goodreads G
        public const string Google_Logo = "\xf1a0"; // Google Logo
        public const string Google_Drive = "\xf3aa"; // Google Drive
        public const string Google_Play = "\xf3ab"; // Google Play
        public const string Google_Plus = "\xf2b3"; // Google Plus
        public const string Google_Plus_G = "\xf0d5"; // Google Plus G
        public const string Google_Plus_Square = "\xf0d4"; // Google Plus Square
        public const string Google_Wallet = "\xf1ee"; // Google Wallet
        public const string Gopuram = "\xf664"; // Gopuram
        public const string Graduation_Cap = "\xf19d"; // Graduation Cap
        public const string Gratipay_Gittip = "\xf184"; // Gratipay (Gittip)
        public const string Grav = "\xf2d6"; // Grav
        public const string Greater_Than = "\xf531"; // Greater Than
        public const string Greater_Than_Equal_To = "\xf532"; // Greater Than Equal To
        public const string Grimacing_Face = "\xf57f"; // Grimacing Face
        public const string Grinning_Face = "\xf580"; // Grinning Face
        public const string Alternate_Grinning_Face = "\xf581"; // Alternate Grinning Face
        public const string Grinning_Face_With_Smiling_Eyes = "\xf582"; // Grinning Face With Smiling Eyes
        public const string Grinning_Face_With_Sweat = "\xf583"; // Grinning Face With Sweat
        public const string Smiling_Face_With_Hearteyes = "\xf584"; // Smiling Face With Heart-Eyes
        public const string Grinning_Squinting_Face = "\xf585"; // Grinning Squinting Face
        public const string Rolling_On_The_Floor_Laughing = "\xf586"; // Rolling on the Floor Laughing
        public const string Starstruck = "\xf587"; // Star-Struck
        public const string Face_With_Tears_Of_Joy = "\xf588"; // Face With Tears of Joy
        public const string Face_With_Tongue = "\xf589"; // Face With Tongue
        public const string Squinting_Face_With_Tongue = "\xf58a"; // Squinting Face With Tongue
        public const string Winking_Face_With_Tongue = "\xf58b"; // Winking Face With Tongue
        public const string Grinning_Winking_Face = "\xf58c"; // Grinning Winking Face
        public const string Grip_Horizontal = "\xf58d"; // Grip Horizontal
        public const string Grip_Lines = "\xf7a4"; // Grip Lines
        public const string Grip_Lines_Vertical = "\xf7a5"; // Grip Lines Vertical
        public const string Grip_Vertical = "\xf58e"; // Grip Vertical
        public const string Gripfire_Inc = "\xf3ac"; // Gripfire, Inc.
        public const string Grunt = "\xf3ad"; // Grunt
        public const string Guitar = "\xf7a6"; // Guitar
        public const string Gulp = "\xf3ae"; // Gulp
        public const string H_Square = "\xf0fd"; // H Square
        public const string Hacker_News = "\xf1d4"; // Hacker News
        public const string Hacker_News_Square = "\xf3af"; // Hacker News Square
        public const string Hackerrank = "\xf5f7"; // Hackerrank
        public const string Hamburger = "\xf805"; // Hamburger
        public const string Hammer = "\xf6e3"; // Hammer
        public const string Hamsa = "\xf665"; // Hamsa
        public const string Hand_Holding = "\xf4bd"; // Hand Holding
        public const string Hand_Holding_Heart = "\xf4be"; // Hand Holding Heart
        public const string Hand_Holding_Us_Dollar = "\xf4c0"; // Hand Holding US Dollar
        public const string Lizard_Hand = "\xf258"; // Lizard (Hand)
        public const string Hand_With_Middle_Finger_Raised = "\xf806"; // Hand with Middle Finger Raised
        public const string Paper_Hand = "\xf256"; // Paper (Hand)
        public const string Peace_Hand = "\xf25b"; // Peace (Hand)
        public const string Hand_Pointing_Down = "\xf0a7"; // Hand Pointing Down
        public const string Hand_Pointing_Left = "\xf0a5"; // Hand Pointing Left
        public const string Hand_Pointing_Right = "\xf0a4"; // Hand Pointing Right
        public const string Hand_Pointing_Up = "\xf0a6"; // Hand Pointing Up
        public const string Pointer_Hand = "\xf25a"; // Pointer (Hand)
        public const string Rock_Hand = "\xf255"; // Rock (Hand)
        public const string Scissors_Hand = "\xf257"; // Scissors (Hand)
        public const string Spock_Hand = "\xf259"; // Spock (Hand)
        public const string Hands = "\xf4c2"; // Hands
        public const string Helping_Hands = "\xf4c4"; // Helping Hands
        public const string Handshake = "\xf2b5"; // Handshake
        public const string Hanukiah = "\xf6e6"; // Hanukiah
        public const string Hard_Hat = "\xf807"; // Hard Hat
        public const string Hashtag = "\xf292"; // Hashtag
        public const string Cowboy_Hat = "\xf8c0"; // Cowboy Hat
        public const string Cowboy_Hat_Side = "\xf8c1"; // Cowboy Hat Side
        public const string Wizards_Hat = "\xf6e8"; // Wizard's Hat
        public const string Hdd = "\xf0a0"; // HDD
        public const string Heading = "\xf1dc"; // heading
        public const string Headphones = "\xf025"; // headphones
        public const string Alternate_Headphones = "\xf58f"; // Alternate Headphones
        public const string Headset = "\xf590"; // Headset
        public const string Heart = "\xf004"; // Heart
        public const string Heart_Broken = "\xf7a9"; // Heart Broken
        public const string Heartbeat = "\xf21e"; // Heartbeat
        public const string Helicopter = "\xf533"; // Helicopter
        public const string Highlighter = "\xf591"; // Highlighter
        public const string Hiking = "\xf6ec"; // Hiking
        public const string Hippo = "\xf6ed"; // Hippo
        public const string Hips = "\xf452"; // Hips
        public const string Hireahelper = "\xf3b0"; // HireAHelper
        public const string History = "\xf1da"; // History
        public const string Hockey_Puck = "\xf453"; // Hockey Puck
        public const string Holly_Berry = "\xf7aa"; // Holly Berry
        public const string Home = "\xf015"; // home
        public const string Hooli = "\xf427"; // Hooli
        public const string Hornbill = "\xf592"; // Hornbill
        public const string Horse = "\xf6f0"; // Horse
        public const string Horse_Head = "\xf7ab"; // Horse Head
        public const string Hospital = "\xf0f8"; // hospital
        public const string Alternate_Hospital = "\xf47d"; // Alternate Hospital
        public const string Hospital_Symbol = "\xf47e"; // Hospital Symbol
        public const string Hot_Tub = "\xf593"; // Hot Tub
        public const string Hot_Dog = "\xf80f"; // Hot Dog
        public const string Hotel = "\xf594"; // Hotel
        public const string Hotjar = "\xf3b1"; // Hotjar
        public const string Hourglass = "\xf254"; // Hourglass
        public const string Hourglass_End = "\xf253"; // Hourglass End
        public const string Hourglass_Half = "\xf252"; // Hourglass Half
        public const string Hourglass_Start = "\xf251"; // Hourglass Start
        public const string Damaged_House = "\xf6f1"; // Damaged House
        public const string Houzz = "\xf27c"; // Houzz
        public const string Hryvnia = "\xf6f2"; // Hryvnia
        public const string Html_5_Logo = "\xf13b"; // HTML 5 Logo
        public const string Hubspot = "\xf3b2"; // HubSpot
        public const string I_Beam_Cursor = "\xf246"; // I Beam Cursor
        public const string Ice_Cream = "\xf810"; // Ice Cream
        public const string Icicles = "\xf7ad"; // Icicles
        public const string Icons = "\xf86d"; // Icons
        public const string Identification_Badge = "\xf2c1"; // Identification Badge
        public const string Identification_Card = "\xf2c2"; // Identification Card
        public const string Alternate_Identification_Card = "\xf47f"; // Alternate Identification Card
        public const string Ideal = "\xf913"; // iDeal
        public const string Igloo = "\xf7ae"; // Igloo
        public const string Image = "\xf03e"; // Image
        public const string Images = "\xf302"; // Images
        public const string Imdb = "\xf2d8"; // IMDB
        public const string Inbox = "\xf01c"; // inbox
        public const string Indent = "\xf03c"; // Indent
        public const string Industry = "\xf275"; // Industry
        public const string Infinity = "\xf534"; // Infinity
        public const string Info = "\xf129"; // Info
        public const string Info_Circle = "\xf05a"; // Info Circle
        public const string Instagram = "\xf16d"; // Instagram
        public const string Intercom = "\xf7af"; // Intercom
        public const string Internetexplorer = "\xf26b"; // Internet-explorer
        public const string Invision = "\xf7b0"; // InVision
        public const string Ioxhost = "\xf208"; // ioxhost
        public const string Italic = "\xf033"; // italic
        public const string Itchio = "\xf83a"; // itch.io
        public const string Itunes = "\xf3b4"; // iTunes
        public const string Itunes_Note = "\xf3b5"; // Itunes Note
        public const string Java = "\xf4e4"; // Java
        public const string Jedi = "\xf669"; // Jedi
        public const string Jedi_Order = "\xf50e"; // Jedi Order
        public const string Jenkis = "\xf3b6"; // Jenkis
        public const string Jira = "\xf7b1"; // Jira
        public const string Joget = "\xf3b7"; // Joget
        public const string Joint = "\xf595"; // Joint
        public const string Joomla_Logo = "\xf1aa"; // Joomla Logo
        public const string Journal_Of_The_Whills = "\xf66a"; // Journal of the Whills
        public const string Javascript_Js = "\xf3b8"; // JavaScript (JS)
        public const string Javascript_Js_Square = "\xf3b9"; // JavaScript (JS) Square
        public const string Jsfiddle = "\xf1cc"; // jsFiddle
        public const string Kaaba = "\xf66b"; // Kaaba
        public const string Kaggle = "\xf5fa"; // Kaggle
        public const string Key = "\xf084"; // key
        public const string Keybase = "\xf4f5"; // Keybase
        public const string Keyboard = "\xf11c"; // Keyboard
        public const string Keycdn = "\xf3ba"; // KeyCDN
        public const string Khanda = "\xf66d"; // Khanda
        public const string Kickstarter = "\xf3bb"; // Kickstarter
        public const string Kickstarter_K = "\xf3bc"; // Kickstarter K
        public const string Kissing_Face = "\xf596"; // Kissing Face
        public const string Kissing_Face_With_Smiling_Eyes = "\xf597"; // Kissing Face With Smiling Eyes
        public const string Face_Blowing_A_Kiss = "\xf598"; // Face Blowing a Kiss
        public const string Kiwi_Bird = "\xf535"; // Kiwi Bird
        public const string Korvue = "\xf42f"; // KORVUE
        public const string Landmark = "\xf66f"; // Landmark
        public const string Language = "\xf1ab"; // Language
        public const string Laptop = "\xf109"; // Laptop
        public const string Laptop_Code = "\xf5fc"; // Laptop Code
        public const string Laptop_Medical = "\xf812"; // Laptop Medical
        public const string Laravel = "\xf3bd"; // Laravel
        public const string Lastfm = "\xf202"; // last.fm
        public const string Lastfm_Square = "\xf203"; // last.fm Square
        public const string Grinning_Face_With_Big_Eyes = "\xf599"; // Grinning Face With Big Eyes
        public const string Laugh_Face_With_Beaming_Eyes = "\xf59a"; // Laugh Face with Beaming Eyes
        public const string Laughing_Squinting_Face = "\xf59b"; // Laughing Squinting Face
        public const string Laughing_Winking_Face = "\xf59c"; // Laughing Winking Face
        public const string Layer_Group = "\xf5fd"; // Layer Group
        public const string Leaf = "\xf06c"; // leaf
        public const string Leanpub = "\xf212"; // Leanpub
        public const string Lemon = "\xf094"; // Lemon
        public const string Less = "\xf41d"; // Less
        public const string Less_Than = "\xf536"; // Less Than
        public const string Less_Than_Equal_To = "\xf537"; // Less Than Equal To
        public const string Alternate_Level_Down = "\xf3be"; // Alternate Level Down
        public const string Alternate_Level_Up = "\xf3bf"; // Alternate Level Up
        public const string Life_Ring = "\xf1cd"; // Life Ring
        public const string Lightbulb = "\xf0eb"; // Lightbulb
        public const string Line = "\xf3c0"; // Line
        public const string Link = "\xf0c1"; // Link
        public const string Linkedin = "\xf08c"; // LinkedIn
        public const string Linkedin_In = "\xf0e1"; // LinkedIn In
        public const string Linode = "\xf2b8"; // Linode
        public const string Linux = "\xf17c"; // Linux
        public const string Turkish_Lira_Sign = "\xf195"; // Turkish Lira Sign
        public const string List = "\xf03a"; // List
        public const string Alternate_List = "\xf022"; // Alternate List
        public const string Listol = "\xf0cb"; // list-ol
        public const string Listul = "\xf0ca"; // list-ul
        public const string Locationarrow = "\xf124"; // location-arrow
        public const string Lock = "\xf023"; // lock
        public const string Lock_Open = "\xf3c1"; // Lock Open
        public const string Alternate_Long_Arrow_Down = "\xf309"; // Alternate Long Arrow Down
        public const string Alternate_Long_Arrow_Left = "\xf30a"; // Alternate Long Arrow Left
        public const string Alternate_Long_Arrow_Right = "\xf30b"; // Alternate Long Arrow Right
        public const string Alternate_Long_Arrow_Up = "\xf30c"; // Alternate Long Arrow Up
        public const string Low_Vision = "\xf2a8"; // Low Vision
        public const string Luggage_Cart = "\xf59d"; // Luggage Cart
        public const string Lyft = "\xf3c3"; // lyft
        public const string Magento = "\xf3c4"; // Magento
        public const string Magic = "\xf0d0"; // magic
        public const string Magnet = "\xf076"; // magnet
        public const string Mail_Bulk = "\xf674"; // Mail Bulk
        public const string Mailchimp = "\xf59e"; // Mailchimp
        public const string Male = "\xf183"; // Male
        public const string Mandalorian = "\xf50f"; // Mandalorian
        public const string Map = "\xf279"; // Map
        public const string Map_Marked = "\xf59f"; // Map Marked
        public const string Alternate_Map_Marked = "\xf5a0"; // Alternate Map Marked
        public const string Mapmarker = "\xf041"; // map-marker
        public const string Alternate_Map_Marker = "\xf3c5"; // Alternate Map Marker
        public const string Map_Pin = "\xf276"; // Map Pin
        public const string Map_Signs = "\xf277"; // Map Signs
        public const string Markdown = "\xf60f"; // Markdown
        public const string Marker = "\xf5a1"; // Marker
        public const string Mars = "\xf222"; // Mars
        public const string Mars_Double = "\xf227"; // Mars Double
        public const string Mars_Stroke = "\xf229"; // Mars Stroke
        public const string Mars_Stroke_Horizontal = "\xf22b"; // Mars Stroke Horizontal
        public const string Mars_Stroke_Vertical = "\xf22a"; // Mars Stroke Vertical
        public const string Mask = "\xf6fa"; // Mask
        public const string Mastodon = "\xf4f6"; // Mastodon
        public const string Maxcdn = "\xf136"; // MaxCDN
        public const string Material_Design_For_Bootstrap = "\xf8ca"; // Material Design for Bootstrap
        public const string Medal = "\xf5a2"; // Medal
        public const string Medapps = "\xf3c6"; // MedApps
        public const string Medium = "\xf23a"; // Medium
        public const string Medium_M = "\xf3c7"; // Medium M
        public const string Medkit = "\xf0fa"; // medkit
        public const string Mrt = "\xf3c8"; // MRT
        public const string Meetup = "\xf2e0"; // Meetup
        public const string Megaport = "\xf5a3"; // Megaport
        public const string Neutral_Face = "\xf11a"; // Neutral Face
        public const string Face_Without_Mouth = "\xf5a4"; // Face Without Mouth
        public const string Face_With_Rolling_Eyes = "\xf5a5"; // Face With Rolling Eyes
        public const string Memory = "\xf538"; // Memory
        public const string Mendeley = "\xf7b3"; // Mendeley
        public const string Menorah = "\xf676"; // Menorah
        public const string Mercury = "\xf223"; // Mercury
        public const string Meteor = "\xf753"; // Meteor
        public const string Microblog = "\xf91a"; // Micro.blog
        public const string Microchip = "\xf2db"; // Microchip
        public const string Microphone = "\xf130"; // microphone
        public const string Alternate_Microphone = "\xf3c9"; // Alternate Microphone
        public const string Alternate_Microphone_Slash = "\xf539"; // Alternate Microphone Slash
        public const string Microphone_Slash = "\xf131"; // Microphone Slash
        public const string Microscope = "\xf610"; // Microscope
        public const string Microsoft = "\xf3ca"; // Microsoft
        public const string Minus = "\xf068"; // minus
        public const string Minus_Circle = "\xf056"; // Minus Circle
        public const string Minus_Square = "\xf146"; // Minus Square
        public const string Mitten = "\xf7b5"; // Mitten
        public const string Mix = "\xf3cb"; // Mix
        public const string Mixcloud = "\xf289"; // Mixcloud
        public const string Mizuni = "\xf3cc"; // Mizuni
        public const string Mobile_Phone = "\xf10b"; // Mobile Phone
        public const string Alternate_Mobile = "\xf3cd"; // Alternate Mobile
        public const string Modx = "\xf285"; // MODX
        public const string Monero = "\xf3d0"; // Monero
        public const string Money_Bill = "\xf0d6"; // Money Bill
        public const string Alternate_Money_Bill = "\xf3d1"; // Alternate Money Bill
        public const string Wavy_Money_Bill = "\xf53a"; // Wavy Money Bill
        public const string Alternate_Wavy_Money_Bill = "\xf53b"; // Alternate Wavy Money Bill
        public const string Money_Check = "\xf53c"; // Money Check
        public const string Alternate_Money_Check = "\xf53d"; // Alternate Money Check
        public const string Monument = "\xf5a6"; // Monument
        public const string Moon = "\xf186"; // Moon
        public const string Mortar_Pestle = "\xf5a7"; // Mortar Pestle
        public const string Mosque = "\xf678"; // Mosque
        public const string Motorcycle = "\xf21c"; // Motorcycle
        public const string Mountain = "\xf6fc"; // Mountain
        public const string Mouse = "\xf8cc"; // Mouse
        public const string Mouse_Pointer = "\xf245"; // Mouse Pointer
        public const string Mug_Hot = "\xf7b6"; // Mug Hot
        public const string Music = "\xf001"; // Music
        public const string Napster = "\xf3d2"; // Napster
        public const string Neos = "\xf612"; // Neos
        public const string Wired_Network = "\xf6ff"; // Wired Network
        public const string Neuter = "\xf22c"; // Neuter
        public const string Newspaper = "\xf1ea"; // Newspaper
        public const string Nimblr = "\xf5a8"; // Nimblr
        public const string Nodejs = "\xf419"; // Node.js
        public const string Nodejs_Js = "\xf3d3"; // Node.js JS
        public const string Not_Equal = "\xf53e"; // Not Equal
        public const string Medical_Notes = "\xf481"; // Medical Notes
        public const string Npm = "\xf3d4"; // npm
        public const string Ns8 = "\xf3d5"; // NS8
        public const string Nutritionix = "\xf3d6"; // Nutritionix
        public const string Object_Group = "\xf247"; // Object Group
        public const string Object_Ungroup = "\xf248"; // Object Ungroup
        public const string Odnoklassniki = "\xf263"; // Odnoklassniki
        public const string Odnoklassniki_Square = "\xf264"; // Odnoklassniki Square
        public const string Oil_Can = "\xf613"; // Oil Can
        public const string Old_Republic = "\xf510"; // Old Republic
        public const string Om = "\xf679"; // Om
        public const string Opencart = "\xf23d"; // OpenCart
        public const string Openid = "\xf19b"; // OpenID
        public const string Opera = "\xf26a"; // Opera
        public const string Optin_Monster = "\xf23c"; // Optin Monster
        public const string Orcid = "\xf8d2"; // ORCID
        public const string Open_Source_Initiative = "\xf41a"; // Open Source Initiative
        public const string Otter = "\xf700"; // Otter
        public const string Outdent = "\xf03b"; // Outdent
        public const string Page4_Corporation = "\xf3d7"; // page4 Corporation
        public const string Pagelines = "\xf18c"; // Pagelines
        public const string Pager = "\xf815"; // Pager
        public const string Paint_Brush = "\xf1fc"; // Paint Brush
        public const string Paint_Roller = "\xf5aa"; // Paint Roller
        public const string Palette = "\xf53f"; // Palette
        public const string Palfed = "\xf3d8"; // Palfed
        public const string Pallet = "\xf482"; // Pallet
        public const string Paper_Plane = "\xf1d8"; // Paper Plane
        public const string Paperclip = "\xf0c6"; // Paperclip
        public const string Parachute_Box = "\xf4cd"; // Parachute Box
        public const string Paragraph = "\xf1dd"; // paragraph
        public const string Parking = "\xf540"; // Parking
        public const string Passport = "\xf5ab"; // Passport
        public const string Pastafarianism = "\xf67b"; // Pastafarianism
        public const string Paste = "\xf0ea"; // Paste
        public const string Patreon = "\xf3d9"; // Patreon
        public const string Pause = "\xf04c"; // pause
        public const string Pause_Circle = "\xf28b"; // Pause Circle
        public const string Paw = "\xf1b0"; // Paw
        public const string Paypal = "\xf1ed"; // Paypal
        public const string Peace = "\xf67c"; // Peace
        public const string Pen = "\xf304"; // Pen
        public const string Alternate_Pen = "\xf305"; // Alternate Pen
        public const string Pen_Fancy = "\xf5ac"; // Pen Fancy
        public const string Pen_Nib = "\xf5ad"; // Pen Nib
        public const string Pen_Square = "\xf14b"; // Pen Square
        public const string Alternate_Pencil = "\xf303"; // Alternate Pencil
        public const string Pencil_Ruler = "\xf5ae"; // Pencil Ruler
        public const string Penny_Arcade = "\xf704"; // Penny Arcade
        public const string People_Carry = "\xf4ce"; // People Carry
        public const string Hot_Pepper = "\xf816"; // Hot Pepper
        public const string Percent = "\xf295"; // Percent
        public const string Percentage = "\xf541"; // Percentage
        public const string Periscope = "\xf3da"; // Periscope
        public const string Person_Entering_Booth = "\xf756"; // Person Entering Booth
        public const string Phabricator = "\xf3db"; // Phabricator
        public const string Phoenix_Framework = "\xf3dc"; // Phoenix Framework
        public const string Phoenix_Squadron = "\xf511"; // Phoenix Squadron
        public const string Phone = "\xf095"; // Phone
        public const string Alternate_Phone = "\xf879"; // Alternate Phone
        public const string Phone_Slash = "\xf3dd"; // Phone Slash
        public const string Phone_Square = "\xf098"; // Phone Square
        public const string Alternate_Phone_Square = "\xf87b"; // Alternate Phone Square
        public const string Phone_Volume = "\xf2a0"; // Phone Volume
        public const string Photo_Video = "\xf87c"; // Photo Video
        public const string Php = "\xf457"; // PHP
        public const string Pied_Piper_Logo = "\xf2ae"; // Pied Piper Logo
        public const string Alternate_Pied_Piper_Logo_Old = "\xf1a8"; // Alternate Pied Piper Logo (Old)
        public const string Pied_Piper_Hat_Old = "\xf4e5"; // Pied Piper Hat (Old)
        public const string Pied_Piper_Pp_Logo_Old = "\xf1a7"; // Pied Piper PP Logo (Old)
        public const string Pied_Piper_Square_Logo_Old = "\xf91e"; // Pied Piper Square Logo (Old)
        public const string Piggy_Bank = "\xf4d3"; // Piggy Bank
        public const string Pills = "\xf484"; // Pills
        public const string Pinterest = "\xf0d2"; // Pinterest
        public const string Pinterest_P = "\xf231"; // Pinterest P
        public const string Pinterest_Square = "\xf0d3"; // Pinterest Square
        public const string Pizza_Slice = "\xf818"; // Pizza Slice
        public const string Place_Of_Worship = "\xf67f"; // Place of Worship
        public const string Plane = "\xf072"; // plane
        public const string Plane_Arrival = "\xf5af"; // Plane Arrival
        public const string Plane_Departure = "\xf5b0"; // Plane Departure
        public const string Play = "\xf04b"; // play
        public const string Play_Circle = "\xf144"; // Play Circle
        public const string Playstation = "\xf3df"; // PlayStation
        public const string Plug = "\xf1e6"; // Plug
        public const string Plus = "\xf067"; // plus
        public const string Plus_Circle = "\xf055"; // Plus Circle
        public const string Plus_Square = "\xf0fe"; // Plus Square
        public const string Podcast = "\xf2ce"; // Podcast
        public const string Poll = "\xf681"; // Poll
        public const string Poll_H = "\xf682"; // Poll H
        public const string Poo = "\xf2fe"; // Poo
        public const string Poo_Storm = "\xf75a"; // Poo Storm
        public const string Poop = "\xf619"; // Poop
        public const string Portrait = "\xf3e0"; // Portrait
        public const string Pound_Sign = "\xf154"; // Pound Sign
        public const string Power_Off = "\xf011"; // Power Off
        public const string Pray = "\xf683"; // Pray
        public const string Praying_Hands = "\xf684"; // Praying Hands
        public const string Prescription = "\xf5b1"; // Prescription
        public const string Prescription_Bottle = "\xf485"; // Prescription Bottle
        public const string Alternate_Prescription_Bottle = "\xf486"; // Alternate Prescription Bottle
        public const string Print = "\xf02f"; // print
        public const string Procedures = "\xf487"; // Procedures
        public const string Product_Hunt = "\xf288"; // Product Hunt
        public const string Project_Diagram = "\xf542"; // Project Diagram
        public const string Pushed = "\xf3e1"; // Pushed
        public const string Puzzle_Piece = "\xf12e"; // Puzzle Piece
        public const string Python = "\xf3e2"; // Python
        public const string Qq = "\xf1d6"; // QQ
        public const string Qrcode = "\xf029"; // qrcode
        public const string Question = "\xf128"; // Question
        public const string Question_Circle = "\xf059"; // Question Circle
        public const string Quidditch = "\xf458"; // Quidditch
        public const string Quinscape = "\xf459"; // QuinScape
        public const string Quora = "\xf2c4"; // Quora
        public const string Quoteleft = "\xf10d"; // quote-left
        public const string Quoteright = "\xf10e"; // quote-right
        public const string Quran = "\xf687"; // Quran
        public const string R_Project = "\xf4f7"; // R Project
        public const string Radiation = "\xf7b9"; // Radiation
        public const string Alternate_Radiation = "\xf7ba"; // Alternate Radiation
        public const string Rainbow = "\xf75b"; // Rainbow
        public const string Random = "\xf074"; // random
        public const string Raspberry_Pi = "\xf7bb"; // Raspberry Pi
        public const string Ravelry = "\xf2d9"; // Ravelry
        public const string React = "\xf41b"; // React
        public const string Reacteurope = "\xf75d"; // ReactEurope
        public const string Readme = "\xf4d5"; // ReadMe
        public const string Rebel_Alliance = "\xf1d0"; // Rebel Alliance
        public const string Receipt = "\xf543"; // Receipt
        public const string Record_Vinyl = "\xf8d9"; // Record Vinyl
        public const string Recycle = "\xf1b8"; // Recycle
        public const string Red_River = "\xf3e3"; // red river
        public const string Reddit_Logo = "\xf1a1"; // reddit Logo
        public const string Reddit_Alien = "\xf281"; // reddit Alien
        public const string Reddit_Square = "\xf1a2"; // reddit Square
        public const string Redhat = "\xf7bc"; // Redhat
        public const string Redo = "\xf01e"; // Redo
        public const string Alternate_Redo = "\xf2f9"; // Alternate Redo
        public const string Registered_Trademark = "\xf25d"; // Registered Trademark
        public const string Remove_Format = "\xf87d"; // Remove Format
        public const string Renren = "\xf18b"; // Renren
        public const string Reply = "\xf3e5"; // Reply
        public const string Replyall = "\xf122"; // reply-all
        public const string Replyd = "\xf3e6"; // replyd
        public const string Republican = "\xf75e"; // Republican
        public const string Researchgate = "\xf4f8"; // Researchgate
        public const string Resolving = "\xf3e7"; // Resolving
        public const string Restroom = "\xf7bd"; // Restroom
        public const string Retweet = "\xf079"; // Retweet
        public const string Revio = "\xf5b2"; // Rev.io
        public const string Ribbon = "\xf4d6"; // Ribbon
        public const string Ring = "\xf70b"; // Ring
        public const string Road = "\xf018"; // road
        public const string Robot = "\xf544"; // Robot
        public const string Rocket = "\xf135"; // rocket
        public const string Rocketchat = "\xf3e8"; // Rocket.Chat
        public const string Rockrms = "\xf3e9"; // Rockrms
        public const string Route = "\xf4d7"; // Route
        public const string Rss = "\xf09e"; // rss
        public const string Rss_Square = "\xf143"; // RSS Square
        public const string Ruble_Sign = "\xf158"; // Ruble Sign
        public const string Ruler = "\xf545"; // Ruler
        public const string Ruler_Combined = "\xf546"; // Ruler Combined
        public const string Ruler_Horizontal = "\xf547"; // Ruler Horizontal
        public const string Ruler_Vertical = "\xf548"; // Ruler Vertical
        public const string Running = "\xf70c"; // Running
        public const string Indian_Rupee_Sign = "\xf156"; // Indian Rupee Sign
        public const string Crying_Face = "\xf5b3"; // Crying Face
        public const string Loudly_Crying_Face = "\xf5b4"; // Loudly Crying Face
        public const string Safari = "\xf267"; // Safari
        public const string Salesforce = "\xf83b"; // Salesforce
        public const string Sass = "\xf41e"; // Sass
        public const string Satellite = "\xf7bf"; // Satellite
        public const string Satellite_Dish = "\xf7c0"; // Satellite Dish
        public const string Save = "\xf0c7"; // Save
        public const string Schlix = "\xf3ea"; // SCHLIX
        public const string School = "\xf549"; // School
        public const string Screwdriver = "\xf54a"; // Screwdriver
        public const string Scribd = "\xf28a"; // Scribd
        public const string Scroll = "\xf70e"; // Scroll
        public const string Sd_Card = "\xf7c2"; // Sd Card
        public const string Search = "\xf002"; // Search
        public const string Search_Dollar = "\xf688"; // Search Dollar
        public const string Search_Location = "\xf689"; // Search Location
        public const string Search_Minus = "\xf010"; // Search Minus
        public const string Search_Plus = "\xf00e"; // Search Plus
        public const string Searchengin = "\xf3eb"; // Searchengin
        public const string Seedling = "\xf4d8"; // Seedling
        public const string Sellcast = "\xf2da"; // Sellcast
        public const string Sellsy = "\xf213"; // Sellsy
        public const string Server = "\xf233"; // Server
        public const string Servicestack = "\xf3ec"; // Servicestack
        public const string Shapes = "\xf61f"; // Shapes
        public const string Share = "\xf064"; // Share
        public const string Alternate_Share = "\xf1e0"; // Alternate Share
        public const string Alternate_Share_Square = "\xf1e1"; // Alternate Share Square
        public const string Share_Square = "\xf14d"; // Share Square
        public const string Shekel_Sign = "\xf20b"; // Shekel Sign
        public const string Alternate_Shield = "\xf3ed"; // Alternate Shield
        public const string Ship = "\xf21a"; // Ship
        public const string Shipping_Fast = "\xf48b"; // Shipping Fast
        public const string Shirts_In_Bulk = "\xf214"; // Shirts in Bulk
        public const string Shoe_Prints = "\xf54b"; // Shoe Prints
        public const string Shopping_Bag = "\xf290"; // Shopping Bag
        public const string Shopping_Basket = "\xf291"; // Shopping Basket
        public const string Shoppingcart = "\xf07a"; // shopping-cart
        public const string Shopware = "\xf5b5"; // Shopware
        public const string Shower = "\xf2cc"; // Shower
        public const string Shuttle_Van = "\xf5b6"; // Shuttle Van
        public const string Sign = "\xf4d9"; // Sign
        public const string Alternate_Sign_In = "\xf2f6"; // Alternate Sign In
        public const string Sign_Language = "\xf2a7"; // Sign Language
        public const string Alternate_Sign_Out = "\xf2f5"; // Alternate Sign Out
        public const string Signal = "\xf012"; // signal
        public const string Signature = "\xf5b7"; // Signature
        public const string Sim_Card = "\xf7c4"; // SIM Card
        public const string Simplybuilt = "\xf215"; // SimplyBuilt
        public const string Sistrix = "\xf3ee"; // SISTRIX
        public const string Sitemap = "\xf0e8"; // Sitemap
        public const string Sith = "\xf512"; // Sith
        public const string Skating = "\xf7c5"; // Skating
        public const string Sketch = "\xf7c6"; // Sketch
        public const string Skiing = "\xf7c9"; // Skiing
        public const string Skiing_Nordic = "\xf7ca"; // Skiing Nordic
        public const string Skull = "\xf54c"; // Skull
        public const string Skull_Crossbones = "\xf714"; // Skull & Crossbones
        public const string Skyatlas = "\xf216"; // skyatlas
        public const string Skype = "\xf17e"; // Skype
        public const string Slack_Logo = "\xf198"; // Slack Logo
        public const string Slack_Hashtag = "\xf3ef"; // Slack Hashtag
        public const string Slash = "\xf715"; // Slash
        public const string Sleigh = "\xf7cc"; // Sleigh
        public const string Horizontal_Sliders = "\xf1de"; // Horizontal Sliders
        public const string Slideshare = "\xf1e7"; // Slideshare
        public const string Smiling_Face = "\xf118"; // Smiling Face
        public const string Beaming_Face_With_Smiling_Eyes = "\xf5b8"; // Beaming Face With Smiling Eyes
        public const string Winking_Face = "\xf4da"; // Winking Face
        public const string Smog = "\xf75f"; // Smog
        public const string Smoking = "\xf48d"; // Smoking
        public const string Smoking_Ban = "\xf54d"; // Smoking Ban
        public const string Sms = "\xf7cd"; // SMS
        public const string Snapchat = "\xf2ab"; // Snapchat
        public const string Snapchat_Ghost = "\xf2ac"; // Snapchat Ghost
        public const string Snapchat_Square = "\xf2ad"; // Snapchat Square
        public const string Snowboarding = "\xf7ce"; // Snowboarding
        public const string Snowflake = "\xf2dc"; // Snowflake
        public const string Snowman = "\xf7d0"; // Snowman
        public const string Snowplow = "\xf7d2"; // Snowplow
        public const string Socks = "\xf696"; // Socks
        public const string Solar_Panel = "\xf5ba"; // Solar Panel
        public const string Sort = "\xf0dc"; // Sort
        public const string Sort_Alphabetical_Down = "\xf15d"; // Sort Alphabetical Down
        public const string Alternate_Sort_Alphabetical_Down = "\xf881"; // Alternate Sort Alphabetical Down
        public const string Sort_Alphabetical_Up = "\xf15e"; // Sort Alphabetical Up
        public const string Alternate_Sort_Alphabetical_Up = "\xf882"; // Alternate Sort Alphabetical Up
        public const string Sort_Amount_Down = "\xf160"; // Sort Amount Down
        public const string Alternate_Sort_Amount_Down = "\xf884"; // Alternate Sort Amount Down
        public const string Sort_Amount_Up = "\xf161"; // Sort Amount Up
        public const string Alternate_Sort_Amount_Up = "\xf885"; // Alternate Sort Amount Up
        public const string Sort_Down_Descending = "\xf0dd"; // Sort Down (Descending)
        public const string Sort_Numeric_Down = "\xf162"; // Sort Numeric Down
        public const string Alternate_Sort_Numeric_Down = "\xf886"; // Alternate Sort Numeric Down
        public const string Sort_Numeric_Up = "\xf163"; // Sort Numeric Up
        public const string Alternate_Sort_Numeric_Up = "\xf887"; // Alternate Sort Numeric Up
        public const string Sort_Up_Ascending = "\xf0de"; // Sort Up (Ascending)
        public const string Soundcloud = "\xf1be"; // SoundCloud
        public const string Sourcetree = "\xf7d3"; // Sourcetree
        public const string Spa = "\xf5bb"; // Spa
        public const string Space_Shuttle = "\xf197"; // Space Shuttle
        public const string Speakap = "\xf3f3"; // Speakap
        public const string Speaker_Deck = "\xf83c"; // Speaker Deck
        public const string Spell_Check = "\xf891"; // Spell Check
        public const string Spider = "\xf717"; // Spider
        public const string Spinner = "\xf110"; // Spinner
        public const string Splotch = "\xf5bc"; // Splotch
        public const string Spotify = "\xf1bc"; // Spotify
        public const string Spray_Can = "\xf5bd"; // Spray Can
        public const string Square = "\xf0c8"; // Square
        public const string Square_Full = "\xf45c"; // Square Full
        public const string Alternate_Square_Root = "\xf698"; // Alternate Square Root
        public const string Squarespace = "\xf5be"; // Squarespace
        public const string Stack_Exchange = "\xf18d"; // Stack Exchange
        public const string Stack_Overflow = "\xf16c"; // Stack Overflow
        public const string Stackpath = "\xf842"; // Stackpath
        public const string Stamp = "\xf5bf"; // Stamp
        public const string Star = "\xf005"; // Star
        public const string Star_And_Crescent = "\xf699"; // Star and Crescent
        public const string Starhalf = "\xf089"; // star-half
        public const string Alternate_Star_Half = "\xf5c0"; // Alternate Star Half
        public const string Star_Of_David = "\xf69a"; // Star of David
        public const string Star_Of_Life = "\xf621"; // Star of Life
        public const string Staylinked = "\xf3f5"; // StayLinked
        public const string Steam = "\xf1b6"; // Steam
        public const string Steam_Square = "\xf1b7"; // Steam Square
        public const string Steam_Symbol = "\xf3f6"; // Steam Symbol
        public const string Stepbackward = "\xf048"; // step-backward
        public const string Stepforward = "\xf051"; // step-forward
        public const string Stethoscope = "\xf0f1"; // Stethoscope
        public const string Sticker_Mule = "\xf3f7"; // Sticker Mule
        public const string Sticky_Note = "\xf249"; // Sticky Note
        public const string Stop = "\xf04d"; // stop
        public const string Stop_Circle = "\xf28d"; // Stop Circle
        public const string Stopwatch = "\xf2f2"; // Stopwatch
        public const string Store = "\xf54e"; // Store
        public const string Alternate_Store = "\xf54f"; // Alternate Store
        public const string Strava = "\xf428"; // Strava
        public const string Stream = "\xf550"; // Stream
        public const string Street_View = "\xf21d"; // Street View
        public const string Strikethrough = "\xf0cc"; // Strikethrough
        public const string Stripe = "\xf429"; // Stripe
        public const string Stripe_S = "\xf42a"; // Stripe S
        public const string Stroopwafel = "\xf551"; // Stroopwafel
        public const string Studio_Vinari = "\xf3f8"; // Studio Vinari
        public const string Stumbleupon_Logo = "\xf1a4"; // StumbleUpon Logo
        public const string Stumbleupon_Circle = "\xf1a3"; // StumbleUpon Circle
        public const string Subscript = "\xf12c"; // subscript
        public const string Subway = "\xf239"; // Subway
        public const string Suitcase = "\xf0f2"; // Suitcase
        public const string Suitcase_Rolling = "\xf5c1"; // Suitcase Rolling
        public const string Sun = "\xf185"; // Sun
        public const string Superpowers = "\xf2dd"; // Superpowers
        public const string Superscript = "\xf12b"; // superscript
        public const string Supple = "\xf3f9"; // Supple
        public const string Hushed_Face = "\xf5c2"; // Hushed Face
        public const string Suse = "\xf7d6"; // Suse
        public const string Swatchbook = "\xf5c3"; // Swatchbook
        public const string Swift = "\xf8e1"; // Swift
        public const string Swimmer = "\xf5c4"; // Swimmer
        public const string Swimming_Pool = "\xf5c5"; // Swimming Pool
        public const string Symfony = "\xf83d"; // Symfony
        public const string Synagogue = "\xf69b"; // Synagogue
        public const string Sync = "\xf021"; // Sync
        public const string Alternate_Sync = "\xf2f1"; // Alternate Sync
        public const string Syringe = "\xf48e"; // Syringe
        public const string Table = "\xf0ce"; // table
        public const string Table_Tennis = "\xf45d"; // Table Tennis
        public const string Tablet = "\xf10a"; // tablet
        public const string Alternate_Tablet = "\xf3fa"; // Alternate Tablet
        public const string Tablets = "\xf490"; // Tablets
        public const string Alternate_Tachometer = "\xf3fd"; // Alternate Tachometer
        public const string Tag = "\xf02b"; // tag
        public const string Tags = "\xf02c"; // tags
        public const string Tape = "\xf4db"; // Tape
        public const string Tasks = "\xf0ae"; // Tasks
        public const string Taxi = "\xf1ba"; // Taxi
        public const string Teamspeak = "\xf4f9"; // TeamSpeak
        public const string Teeth = "\xf62e"; // Teeth
        public const string Teeth_Open = "\xf62f"; // Teeth Open
        public const string Telegram = "\xf2c6"; // Telegram
        public const string Telegram_Plane = "\xf3fe"; // Telegram Plane
        public const string High_Temperature = "\xf769"; // High Temperature
        public const string Low_Temperature = "\xf76b"; // Low Temperature
        public const string Tencent_Weibo = "\xf1d5"; // Tencent Weibo
        public const string Tenge = "\xf7d7"; // Tenge
        public const string Terminal = "\xf120"; // Terminal
        public const string Textheight = "\xf034"; // text-height
        public const string Text_Width = "\xf035"; // Text Width
        public const string Th = "\xf00a"; // th
        public const string Thlarge = "\xf009"; // th-large
        public const string Thlist = "\xf00b"; // th-list
        public const string The_Red_Yeti = "\xf69d"; // The Red Yeti
        public const string Theater_Masks = "\xf630"; // Theater Masks
        public const string Themeco = "\xf5c6"; // Themeco
        public const string Themeisle = "\xf2b2"; // ThemeIsle
        public const string Thermometer = "\xf491"; // Thermometer
        public const string Thermometer_Empty = "\xf2cb"; // Thermometer Empty
        public const string Thermometer_Full = "\xf2c7"; // Thermometer Full
        public const string Thermometer_12_Full = "\xf2c9"; // Thermometer 1/2 Full
        public const string Thermometer_14_Full = "\xf2ca"; // Thermometer 1/4 Full
        public const string Thermometer_34_Full = "\xf2c8"; // Thermometer 3/4 Full
        public const string Think_Peaks = "\xf731"; // Think Peaks
        public const string Thumbsdown = "\xf165"; // thumbs-down
        public const string Thumbsup = "\xf164"; // thumbs-up
        public const string Thumbtack = "\xf08d"; // Thumbtack
        public const string Alternate_Ticket = "\xf3ff"; // Alternate Ticket
        public const string Times = "\xf00d"; // Times
        public const string Times_Circle = "\xf057"; // Times Circle
        public const string Tint = "\xf043"; // tint
        public const string Tint_Slash = "\xf5c7"; // Tint Slash
        public const string Tired_Face = "\xf5c8"; // Tired Face
        public const string Toggle_Off = "\xf204"; // Toggle Off
        public const string Toggle_On = "\xf205"; // Toggle On
        public const string Toilet = "\xf7d8"; // Toilet
        public const string Toilet_Paper = "\xf71e"; // Toilet Paper
        public const string Toolbox = "\xf552"; // Toolbox
        public const string Tools = "\xf7d9"; // Tools
        public const string Tooth = "\xf5c9"; // Tooth
        public const string Torah = "\xf6a0"; // Torah
        public const string Torii_Gate = "\xf6a1"; // Torii Gate
        public const string Tractor = "\xf722"; // Tractor
        public const string Trade_Federation = "\xf513"; // Trade Federation
        public const string Trademark = "\xf25c"; // Trademark
        public const string Traffic_Light = "\xf637"; // Traffic Light
        public const string Trailer = "\xf941"; // Trailer
        public const string Train = "\xf238"; // Train
        public const string Tram = "\xf7da"; // Tram
        public const string Transgender = "\xf224"; // Transgender
        public const string Alternate_Transgender = "\xf225"; // Alternate Transgender
        public const string Trash = "\xf1f8"; // Trash
        public const string Alternate_Trash = "\xf2ed"; // Alternate Trash
        public const string Trash_Restore = "\xf829"; // Trash Restore
        public const string Alternative_Trash_Restore = "\xf82a"; // Alternative Trash Restore
        public const string Tree = "\xf1bb"; // Tree
        public const string Trello = "\xf181"; // Trello
        public const string Tripadvisor = "\xf262"; // TripAdvisor
        public const string Trophy = "\xf091"; // trophy
        public const string Truck = "\xf0d1"; // truck
        public const string Truck_Loading = "\xf4de"; // Truck Loading
        public const string Truck_Monster = "\xf63b"; // Truck Monster
        public const string Truck_Moving = "\xf4df"; // Truck Moving
        public const string Truck_Side = "\xf63c"; // Truck Side
        public const string Tshirt = "\xf553"; // T-Shirt
        public const string Tty = "\xf1e4"; // TTY
        public const string Tumblr = "\xf173"; // Tumblr
        public const string Tumblr_Square = "\xf174"; // Tumblr Square
        public const string Television = "\xf26c"; // Television
        public const string Twitch = "\xf1e8"; // Twitch
        public const string Twitter = "\xf099"; // Twitter
        public const string Twitter_Square = "\xf081"; // Twitter Square
        public const string Typo3 = "\xf42b"; // Typo3
        public const string Uber = "\xf402"; // Uber
        public const string Ubuntu = "\xf7df"; // Ubuntu
        public const string Uikit = "\xf403"; // UIkit
        public const string Umbraco = "\xf8e8"; // Umbraco
        public const string Umbrella = "\xf0e9"; // Umbrella
        public const string Umbrella_Beach = "\xf5ca"; // Umbrella Beach
        public const string Underline = "\xf0cd"; // Underline
        public const string Undo = "\xf0e2"; // Undo
        public const string Alternate_Undo = "\xf2ea"; // Alternate Undo
        public const string Uniregistry = "\xf404"; // Uniregistry
        public const string Unity_3d = "\xf949"; // Unity 3D
        public const string Universal_Access = "\xf29a"; // Universal Access
        public const string University = "\xf19c"; // University
        public const string Unlink = "\xf127"; // unlink
        public const string Unlock = "\xf09c"; // unlock
        public const string Alternate_Unlock = "\xf13e"; // Alternate Unlock
        public const string Untappd = "\xf405"; // Untappd
        public const string Upload = "\xf093"; // Upload
        public const string Ups = "\xf7e0"; // UPS
        public const string Usb = "\xf287"; // USB
        public const string User = "\xf007"; // User
        public const string Alternate_User = "\xf406"; // Alternate User
        public const string Alternate_User_Slash = "\xf4fa"; // Alternate User Slash
        public const string User_Astronaut = "\xf4fb"; // User Astronaut
        public const string User_Check = "\xf4fc"; // User Check
        public const string User_Circle = "\xf2bd"; // User Circle
        public const string User_Clock = "\xf4fd"; // User Clock
        public const string User_Cog = "\xf4fe"; // User Cog
        public const string User_Edit = "\xf4ff"; // User Edit
        public const string User_Friends = "\xf500"; // User Friends
        public const string User_Graduate = "\xf501"; // User Graduate
        public const string User_Injured = "\xf728"; // User Injured
        public const string User_Lock = "\xf502"; // User Lock
        public const string Doctor = "\xf0f0"; // Doctor
        public const string User_Minus = "\xf503"; // User Minus
        public const string User_Ninja = "\xf504"; // User Ninja
        public const string Nurse = "\xf82f"; // Nurse
        public const string User_Plus = "\xf234"; // User Plus
        public const string User_Secret = "\xf21b"; // User Secret
        public const string User_Shield = "\xf505"; // User Shield
        public const string User_Slash = "\xf506"; // User Slash
        public const string User_Tag = "\xf507"; // User Tag
        public const string User_Tie = "\xf508"; // User Tie
        public const string Remove_User = "\xf235"; // Remove User
        public const string Users = "\xf0c0"; // Users
        public const string Users_Cog = "\xf509"; // Users Cog
        public const string United_States_Postal_Service = "\xf7e1"; // United States Postal Service
        public const string Ussunnah_Foundation = "\xf407"; // us-Sunnah Foundation
        public const string Utensil_Spoon = "\xf2e5"; // Utensil Spoon
        public const string Utensils = "\xf2e7"; // Utensils
        public const string Vaadin = "\xf408"; // Vaadin
        public const string Vector_Square = "\xf5cb"; // Vector Square
        public const string Venus = "\xf221"; // Venus
        public const string Venus_Double = "\xf226"; // Venus Double
        public const string Venus_Mars = "\xf228"; // Venus Mars
        public const string Viacoin = "\xf237"; // Viacoin
        public const string Video = "\xf2a9"; // Video
        public const string Video_Square = "\xf2aa"; // Video Square
        public const string Vial = "\xf492"; // Vial
        public const string Vials = "\xf493"; // Vials
        public const string Viber = "\xf409"; // Viber
        public const string Video_2 = "\xf03d"; // Video
        public const string Video_Slash = "\xf4e2"; // Video Slash
        public const string Vihara = "\xf6a7"; // Vihara
        public const string Vimeo = "\xf40a"; // Vimeo
        public const string Vimeo_Square = "\xf194"; // Vimeo Square
        public const string Vimeo_2 = "\xf27d"; // Vimeo
        public const string Vine = "\xf1ca"; // Vine
        public const string Vk = "\xf189"; // VK
        public const string Vnv = "\xf40b"; // VNV
        public const string Voicemail = "\xf897"; // Voicemail
        public const string Volleyball_Ball = "\xf45f"; // Volleyball Ball
        public const string Volume_Down = "\xf027"; // Volume Down
        public const string Volume_Mute = "\xf6a9"; // Volume Mute
        public const string Volume_Off = "\xf026"; // Volume Off
        public const string Volume_Up = "\xf028"; // Volume Up
        public const string Vote_Yea = "\xf772"; // Vote Yea
        public const string Cardboard_Vr = "\xf729"; // Cardboard VR
        public const string Vuejs = "\xf41f"; // Vue.js
        public const string Walking = "\xf554"; // Walking
        public const string Wallet = "\xf555"; // Wallet
        public const string Warehouse = "\xf494"; // Warehouse
        public const string Water = "\xf773"; // Water
        public const string Square_Wave = "\xf83e"; // Square Wave
        public const string Waze = "\xf83f"; // Waze
        public const string Weebly = "\xf5cc"; // Weebly
        public const string Weibo = "\xf18a"; // Weibo
        public const string Weight = "\xf496"; // Weight
        public const string Hanging_Weight = "\xf5cd"; // Hanging Weight
        public const string Weixin_Wechat = "\xf1d7"; // Weixin (WeChat)
        public const string Whats_App = "\xf232"; // What's App
        public const string Whats_App_Square = "\xf40c"; // What's App Square
        public const string Wheelchair = "\xf193"; // Wheelchair
        public const string Whmcs = "\xf40d"; // WHMCS
        public const string Wifi = "\xf1eb"; // WiFi
        public const string Wikipedia_W = "\xf266"; // Wikipedia W
        public const string Wind = "\xf72e"; // Wind
        public const string Window_Close = "\xf410"; // Window Close
        public const string Window_Maximize = "\xf2d0"; // Window Maximize
        public const string Window_Minimize = "\xf2d1"; // Window Minimize
        public const string Window_Restore = "\xf2d2"; // Window Restore
        public const string Windows = "\xf17a"; // Windows
        public const string Wine_Bottle = "\xf72f"; // Wine Bottle
        public const string Wine_Glass = "\xf4e3"; // Wine Glass
        public const string Alternate_Wine_Glas = "\xf5ce"; // Alternate Wine Glas
        public const string Wix = "\xf5cf"; // Wix
        public const string Wizards_Of_The_Coast = "\xf730"; // Wizards of the Coast
        public const string Wolf_Pack_Battalion = "\xf514"; // Wolf Pack Battalion
        public const string Won_Sign = "\xf159"; // Won Sign
        public const string Wordpress_Logo = "\xf19a"; // WordPress Logo
        public const string Wordpress_Simple = "\xf411"; // Wordpress Simple
        public const string Wpbeginner = "\xf297"; // WPBeginner
        public const string Wpexplorer = "\xf2de"; // WPExplorer
        public const string Wpforms = "\xf298"; // WPForms
        public const string Wpressr = "\xf3e4"; // wpressr
        public const string Wrench = "\xf0ad"; // Wrench
        public const string Xray = "\xf497"; // X-Ray
        public const string Xbox = "\xf412"; // Xbox
        public const string Xing = "\xf168"; // Xing
        public const string Xing_Square = "\xf169"; // Xing Square
        public const string Y_Combinator = "\xf23b"; // Y Combinator
        public const string Yahoo_Logo = "\xf19e"; // Yahoo Logo
        public const string Yammer = "\xf840"; // Yammer
        public const string Yandex = "\xf413"; // Yandex
        public const string Yandex_International = "\xf414"; // Yandex International
        public const string Yarn = "\xf7e3"; // Yarn
        public const string Yelp = "\xf1e9"; // Yelp
        public const string Yen_Sign = "\xf157"; // Yen Sign
        public const string Yin_Yang = "\xf6ad"; // Yin Yang
        public const string Yoast = "\xf2b1"; // Yoast
        public const string Youtube = "\xf167"; // YouTube
        public const string Youtube_Square = "\xf431"; // YouTube Square
        public const string Zhihu = "\xf63f"; // Zhihu

    }
}